server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus

logging:
  level:
    com.github.meeteor13.core: DEBUG
